# emailer.py
# Composes and sends the daily digest email via Gmail SMTP.

import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from datetime             import datetime
from config               import GMAIL_SENDER, GMAIL_APP_PASSWORD, RECIPIENT_EMAILS

logger = logging.getLogger(__name__)


def _build_html(analyses: list[dict], run_date: str, no_transcripts: bool) -> str:
    """Build the HTML body of the digest email."""

    header = f"""
    <html><body style="font-family: Arial, sans-serif; color: #1a1a1a; max-width: 900px; margin: auto;">
    <h2 style="color: #003366; border-bottom: 2px solid #003366; padding-bottom: 6px;">
        📋 Earnings Call Transcript Digest — {run_date}
    </h2>
    """

    if no_transcripts:
        body = """
        <p style="color: #555; font-size: 15px;">
            No BSE500 earnings call transcripts were filed yesterday.
        </p>
        """
        return header + body + "</body></html>"

    sections = []
    for i, a in enumerate(analyses):
        company = a["company"]
        qa      = a["standard_qa"].replace("\n", "<br>")
        nw      = a["noteworthy"].replace("\n", "<br>")

        section = f"""
        <div style="margin-top: 30px; border: 1px solid #dde; border-radius: 6px; padding: 20px;">
            <h3 style="color: #003366; margin-top: 0;">
                {i+1}. {company}
            </h3>

            <h4 style="color: #336699; margin-bottom: 4px;">📊 Standard Q&A</h4>
            <div style="background: #f5f8ff; padding: 12px; border-radius: 4px;
                        font-size: 13.5px; line-height: 1.7;">
                {qa}
            </div>

            <h4 style="color: #336699; margin-bottom: 4px; margin-top: 18px;">
                🔍 Analyst Observations
            </h4>
            <div style="background: #fff8f0; padding: 12px; border-radius: 4px;
                        font-size: 13.5px; line-height: 1.7;">
                {nw}
            </div>
        </div>
        """
        sections.append(section)

    footer = f"""
    <p style="margin-top: 30px; color: #999; font-size: 12px;">
        Generated by Earnings Transcript Agent &nbsp;|&nbsp;
        {len(analyses)} transcript(s) analysed &nbsp;|&nbsp;
        {run_date}
    </p>
    </body></html>
    """

    return header + "".join(sections) + footer


def send_digest(analyses: list[dict], failed: list[str] = None,
                from_date: str = None, to_date: str = None) -> bool:
    """
    Compose and send the daily digest.
    analyses: list of dicts from analyser.analyse_transcript()
    failed:   list of company names where analysis/download failed
    from_date / to_date: YYYYMMDD strings for the subject line label
    Returns True if email sent successfully.
    """
    # Build a human-readable date label for subject + header
    def fmt(d):
        return datetime.strptime(d, "%Y%m%d").strftime("%d %b %Y") if d else None

    if from_date and to_date and from_date != to_date:
        date_label = f"{fmt(from_date)} – {fmt(to_date)}"
    elif from_date:
        date_label = fmt(from_date)
    else:
        date_label = datetime.now().strftime("%d %b %Y")

    no_transcripts = len(analyses) == 0

    subject = (
        f"Earnings Digest {date_label} — No new transcripts"
        if no_transcripts
        else f"Earnings Digest {date_label} — {len(analyses)} transcript(s)"
    )

    html_body = _build_html(analyses, date_label, no_transcripts)

    # Append failed companies note if any
    if failed:
        note = (
            f"<p style='color:#c00; font-size:13px;'>"
            f"⚠️ Could not process: {', '.join(failed)}"
            f"</p>"
        )
        html_body = html_body.replace("</body>", note + "</body>")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = GMAIL_SENDER
    msg["To"]      = ", ".join(RECIPIENT_EMAILS)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_SENDER, RECIPIENT_EMAILS, msg.as_string())
        logger.info(f"Digest sent to: {', '.join(RECIPIENT_EMAILS)}")
        return True
    except Exception as e:
        logger.error(f"Email send failed: {e}")
        return False
